# Generated by Django 3.2.3 on 2021-06-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Başlıq')),
                ('content', models.CharField(max_length=100, verbose_name='Məzmun')),
                ('image', models.ImageField(upload_to='', verbose_name='Şəkil')),
            ],
        ),
    ]
