# Generated by Django 3.1.7 on 2021-06-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=30, verbose_name='Ad:')),
                ('sahe', models.IntegerField(verbose_name='Sahesi km ile')),
            ],
        ),
    ]
