# Generated by Django 3.1.7 on 2021-06-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='Basliq:')),
                ('content', models.TextField(verbose_name='Mezmun:')),
                ('image', models.ImageField(upload_to='', verbose_name='Sekil:')),
            ],
        ),
    ]
