# Generated by Django 3.1.7 on 2021-06-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionmodel',
            name='ehali',
            field=models.IntegerField(null=True, verbose_name='Ehali:'),
        ),
    ]
