# Generated by Django 3.2.3 on 2021-06-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_alter_areas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
