# Generated by Django 3.1.7 on 2021-06-29 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0007_auto_20210629_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='RayonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('melumat', models.TextField(verbose_name='Melumat:')),
                ('ad', models.CharField(max_length=35, verbose_name='Rayon Adi:')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.regionmodel', verbose_name='Region:')),
            ],
        ),
    ]
