# Generated by Django 3.1.7 on 2021-06-29 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0009_auto_20210629_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rayonmodel',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rayonlar', to='areas.regionmodel', verbose_name='Region:'),
        ),
    ]
