# Generated by Django 3.1.7 on 2021-07-01 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0010_auto_20210629_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rayonmodel',
            name='sahe',
            field=models.FloatField(blank=True, null=True, verbose_name='Sahesi km² ile:'),
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basliq', models.CharField(max_length=120, verbose_name='Basliq:')),
                ('mezmun', models.TextField(verbose_name='Mezmun:')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('rayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='areas.rayonmodel')),
            ],
        ),
    ]
