# Generated by Django 3.1.7 on 2021-07-03 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('areas', '0012_conversationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='sekil',
            field=models.ImageField(blank=True, null=True, upload_to='koment_sekilleri'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='yazan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversationmodel',
            name='yazan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rayonmodel',
            name='sekil',
            field=models.ImageField(blank=True, null=True, upload_to='rayon_sekilleri'),
        ),
    ]
