# Generated by Django 3.1.7 on 2021-07-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0013_auto_20210703_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='sekil',
            field=models.ImageField(blank=True, default='media/koment_sekiller/default_landscape.png', null=True, upload_to='koment_sekilleri'),
        ),
    ]
