# Generated by Django 3.1.7 on 2021-07-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0015_auto_20210726_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='sekil',
            field=models.ImageField(blank=True, default='/koment_sekilleri/default_landscape.png', null=True, upload_to='koment_sekilleri'),
        ),
    ]
