# Generated by Django 3.1.7 on 2021-07-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='prophile_photo',
            field=models.ImageField(blank=True, default='media/prophile_photos/default_profile', null=True, upload_to='prophile_photos'),
        ),
    ]
